# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target "mbrace Case Study" do
pod 'pop', '~> 1.0'
pod 'CocoaLumberjack', '~> 1.8.1'

# ignore warnings from a specific pod


end
